// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etqngungnrjbbiftcind.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cW5ndW5nbnJqYmJpZnRjaW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Njg5NDEsImV4cCI6MjA2MTM0NDk0MX0.3bsIxBkvlKHFloN_xWWeOGI8FT_pzJavYs6G0Tvcdxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);